name: Deploy Vite Frontend to Azure Static Website

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci
      working-directory: ./frontend

    - name: Build Vite app
      run: npm run build
      working-directory: ./frontend

    - name: Deploy via Azure CLI + SAS
      run: |
        az storage blob upload-batch \
          --account-name jrdemohelloworld \
          --account-key ${{ secrets.AZURE_STORAGE_KEY }} \
          --destination \$web \
          --source .\frontend\dist 
          --overwrite
